database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: hello
  connectionTimeoutMillis: 3000
  app_db_client: knex
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback
runtimeConfig:
  entrypoints:
    - dist/operations.js
http:
  cors_middleware: true
  credentials: true
  allowed_origins:
    - http://localhost:5173
  
